Add camera control gui functionality
MickHarrigan/uhdrtz-rust pull request #72
Opened 2023-05-01 01:35 UTC by dancleaver

2023-05-03 18:57 UTC, MickHarrigan requested changes
Just need to add in the changes for the defaults and it should be good.

2023-05-05 18:41 UTC, dancleaver commented
nice

2023-05-05 18:42 UTC, MickHarrigan approved these changes

2023-05-05 18:43 UTC, MickHarrigan commented
I think that it is all good now!

2023-05-05 18:43 UTC, merged